

//rooms
export const SET_ROOMS_DATA = 'SET_ROOMS_DATA';
export const SET_ROOMS_PAGINATION_LIST_DATA = 'SET_ROOMS_PAGINATION_LIST_DATA';
export const SET_ROOMS_DATA_NULL = 'SET_ROOMS_DATA_NULL';
export const SET_ALL_ROOMS_LOADED_COUNT = 'SET_ALL_ROOMS_LOADED_COUNT';
export const SET_ROOM_DETAILS = 'SET_ROOM_DETAILS'
export const SET_ROOM_PAGINATION_ERROR = 'SET_ROOM_PAGINATION_ERROR'
export const SET_ERROR_DATA_FILTER = 'SET_ERROR_DATA_FILTER'


//user
export const SET_MOBILE_NUMBER = 'SET_MOBILE_NUMBER'
export const SET_MOBILE_AUTH_ERROR_DATA = 'SET_MOBILE_AUTH_ERROR_DATA'
export const MOBILE_AUTH_CODE_SENDED = 'MOBILE_AUTH_CODE_SENDED'
export const MOBILE_AUTH_CODE_SENDED_NULL = 'MOBILE_AUTH_CODE_SENDED_NULL'
export const AUTH = 'AUTH'


//book
export const SET_SCHEDULE_BOOKED_SUCCESS = 'SET_SCHEDULE_BOOKED_SUCCESS'
export const SET_BOOKED_SUCCESS = 'SET_BOOKED_SUCCESS'
export const SET_SCHEDULE_BOOKED_CLEAR = 'SET_SCHEDULE_BOOKED_CLEAR'

//search
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT'
export const SET_SEARCH_TYPE = 'SET_SEARCH_TYPE'
export const SET_SEARCH_WHOM = 'SET_SEARCH_WHOM'
export const SET_SEARCH_PRICE = 'SET_SEARCH_PRICE'
export const SET_SEARCH_ROOM_TYPE = 'SET_SEARCH_ROOM_TYPE'
export const SET_SEARCH_FURNISHED = 'SET_SEARCH_FURNISHED'
export const SET_SEARCH_FILTER_CLEAR = 'SET_SEARCH_FILTER_CLEAR'
// export const SET_SEARCH_TEXT_CLEAR = 'SET_SEARCH_TEXT_CLEAR'












//search
export const SET_SEARCH_DATA = 'SET_SEARCH_DATA'
export const SET_SEARCH_DATA_NULL = 'SET_SEARCH_DATA_NULL'
export const SET_SEARCH_DATA_ERROR = 'SET_SEARCH_DATA_ERROR'
export const SET_SEARCHED = 'SET_SEARCHED'
export const SET_NOT_SEARCHED = 'SET_NOT_SEARCHED'
export const SET_SEARCH_TEXT_AUTO = 'SET_SEARCH_TEXT_AUTO'
export const SET_SEARCH_PLACE_NAME = 'SET_SEARCH_PLACE_NAME'



//filter
export const SET_FILTER_URL_DATA = 'SET_FILTER_URL_DATA'
export const SET_DATA_WITH_TYPES = 'SET_DATA_WITH_TYPES'
export const SET_NO_DATA_WITH_TYPES = 'SET_NO_DATA_WITH_TYPES'
export const SET_FILTER_WITH_TYPE_DATA = 'SET_FILTER_WITH_TYPE_DATA'
export const SET_FILTER_WITH_TYPE_DATA_ERROR = 'SET_FILTER_WITH_TYPE_DATA_ERROR'
export const SET_FILTER_FOR_WHOM_DATA = 'SET_FILTER_FOR_WHOM_DATA'
export const SET_FILTER_FOR_WHOM_DATA_NULL = 'SET_FILTER_FOR_WHOM_DATA_NULL'
export const SET_FILTERED = "SET_FILTERED"
export const SET_NOT_FILTERED = "SET_NOT_FILTERED"
export const SET_FILTER_ERROR = 'SET_FILTER_ERROR'
export const SET_FILTER_ERROR_NULL = 'SET_FILTER_ERROR_NULL'

//locations
export const SET_LOCATIONS = 'SET_LOCATIONS'
export const SET_PAGINATION_LOCATIONS = 'SET_PAGINATION_LOCATIONS'

