export const AUTH = 'AUTH' 

export const LOGIN = 'LOGIN' 

export const ACTIVATE = 'ACTIVATE'
export const USER = 'USER'



//rooms
export const SET_ROOMS_DATA = 'SET_ROOMS_DATA';
export const SET_ROOMS_PAGINATION_LIST_DATA = 'SET_ROOMS_PAGINATION_LIST_DATA';
export const SET_ROOMS_DATA_NULL = 'SET_ROOMS_DATA_NULL';
export const SET_ALL_ROOMS_LOADED_COUNT = 'SET_ALL_ROOMS_LOADED_COUNT';

//search
export const SET_SEARCH_DATA = 'SET_SEARCH_DATA'
export const SET_SEARCH_DATA_NULL = 'SET_SEARCH_DATA_NULL'
export const SET_SEARCH_DATA_ERROR = 'SET_SEARCH_DATA_ERROR'
export const SET_SEARCHED = 'SET_SEARCHED'
export const SET_NOT_SEARCHED = 'SET_NOT_SEARCHED'


//filter
export const SET_DATA_WITH_TYPES = 'SET_DATA_WITH_TYPES'
export const SET_NO_DATA_WITH_TYPES = 'SET_NO_DATA_WITH_TYPES'
export const SET_FILTER_WITH_TYPE_DATA = 'SET_FILTER_WITH_TYPE_DATA'
export const SET_FILTER_WITH_TYPE_DATA_ERROR = 'SET_FILTER_WITH_TYPE_DATA_ERROR'
export const SET_FILTER_FOR_WHOM_DATA = 'SET_FILTER_FOR_WHOM_DATA'
export const SET_FILTER_FOR_WHOM_DATA_NULL = 'SET_FILTER_FOR_WHOM_DATA_NULL'